name: postalhub_client
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  animations: ^2.0.11
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.3
  loading_animation_widget: ^1.2.1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  firebase_auth: ^5.0.0
  provider: ^6.1.2
  firebase_messaging: ^15.0.4
  flutter_secure_storage: ^5.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  visibility_detector: ^0.4.0+2
  another_stepper: ^1.2.2
  flutter_custom_tabs: ^2.1.0
  firebase_app_check: ^0.3.0+4
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/postalhub_logo.jpg
  - assets/gif/not_found.gif
  - assets/gif/search.gif
  - assets/gif/coming_soon.gif
  - assets/images/dev_pic.png
  - assets/images/ic_launcher.png
  - assets/images/werehouse_membershipcard.png
  - assets/images/add_to_google_wallet.png
  - assets/images/add_to_apple_wallet.png
  - assets/images/null_profile.jpg

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
      - family: Kaleko
        fonts:
          - asset: assets/fonts/kaleko_regular.ttf

